# Generated by Django 6.0.8 on 2026-09-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('attendance', models.BooleanField(default=True, verbose_name='asistencia')),
            ],
            options={
                'verbose_name': 'invitado',
                'verbose_name_plural': 'invitados',
                'ordering': ['name', 'id'],
            },
        ),
    ]
